# -*- coding: utf-8 -*-
"""customer churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/121jb09CazvnxQUV4I2erx324fYAFA22U
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/customer_churn_dataset.csv")
df

df.info()

df.head()

df.tail()

df.describe()

df.columns

df.shape

df.isnull()

df.isnull().sum()

df["Gender"].fillna(df["Gender"].mode()[0], inplace=True)

df["ContractType"].fillna(df["ContractType"].mode()[0], inplace=True)

df["PaymentMethod"].fillna(df["PaymentMethod"].mode()[0], inplace=True)

df["InternetService"].fillna("NoService", inplace=True)

df.isnull().sum()

sns.countplot(x='Churn',data=df)
plt.show()

sns.boxplot(x='Churn',y='MonthlyCharges',data=df)
plt.title("Monthly Charges vs Churn")
plt.show

sns.countplot(x='ContractType', hue='Churn', data=df)
plt.title("ContractType vs Churn")
plt.show()

sns.scatterplot(x='Tenure', y='MonthlyCharges', hue='Churn', data=df)
plt.title("Tenure vs Monthly Charges")
plt.show()

df['Churn'].value_counts().plot.pie(autopct='%1.1f%%')
plt.title("Churn Distribution")
plt.ylabel("")
plt.show()

X = df.drop('Churn', axis=1)
y = df['Churn']

df['Gender'] = df['Gender'].map({'Male':1, 'Female':0})

df = pd.get_dummies(df, columns=['ContractType', 'PaymentMethod', 'InternetService'], drop_first=True)

df = df.astype(int)

df

X = df.drop('Churn', axis=1)
y = df['Churn']

X = pd.get_dummies(X, drop_first=True)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight='balanced'
)

rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, fmt='d')
plt.title("Confusion Matrix (Improved Model)")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

from sklearn.metrics import accuracy_score, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

from sklearn.metrics import roc_auc_score

y_prob = rf.predict_proba(X_test)[:,1]
print(roc_auc_score(y_test, y_prob))